
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA LPAR NAME RPAR\n    property : list optproperty \n    \n    optproperty : empty\n                | property\n    \n    list : tuple opttuple\n    \n    opttuple : COMMA tuple opttuple\n             | empty\n    \n    tuple : LPAR NAME COMMA NAME optresname RPAR\n    \n    optresname : COMMA NAME optresname\n               | empty\n    empty : '
    
_lr_action_items = {'LPAR':([0,2,3,8,9,10,12,14,20,],[4,4,-10,-4,4,-6,-10,-5,-7,]),'$end':([1,2,3,5,6,7,8,10,12,14,20,],[0,-10,-10,-1,-2,-3,-4,-6,-10,-5,-7,]),'COMMA':([3,11,12,15,19,20,],[9,13,9,16,16,-7,]),'NAME':([4,13,16,],[11,15,19,]),'RPAR':([15,17,18,19,21,],[-10,20,-9,-10,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'property':([0,2,],[1,7,]),'list':([0,2,],[2,2,]),'tuple':([0,2,9,],[3,3,12,]),'optproperty':([2,],[5,]),'empty':([2,3,12,15,19,],[6,10,10,18,18,]),'opttuple':([3,12,],[8,14,]),'optresname':([15,19,],[17,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> property","S'",1,None,None,None),
  ('property -> list optproperty','property',2,'p_property','parser_properties.py',22),
  ('optproperty -> empty','optproperty',1,'p_optproperty','parser_properties.py',28),
  ('optproperty -> property','optproperty',1,'p_optproperty','parser_properties.py',29),
  ('list -> tuple opttuple','list',2,'p_list','parser_properties.py',36),
  ('opttuple -> COMMA tuple opttuple','opttuple',3,'p_opttuple','parser_properties.py',46),
  ('opttuple -> empty','opttuple',1,'p_opttuple','parser_properties.py',47),
  ('tuple -> LPAR NAME COMMA NAME optresname RPAR','tuple',6,'p_tuple','parser_properties.py',57),
  ('optresname -> COMMA NAME optresname','optresname',3,'p_optresname','parser_properties.py',68),
  ('optresname -> empty','optresname',1,'p_optresname','parser_properties.py',69),
  ('empty -> <empty>','empty',0,'p_empty','parser_properties.py',78),
]
